package com.beco.portalproveedores.bean;

// Generated 14/02/2014 09:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "ATTACHMENT")
public class Attachment implements java.io.Serializable {

	private BigDecimal attachmentId;
	private String name;
	private String type;
	private String route;
	private Set<CommercialAgreement> commercialAgreements = new HashSet<CommercialAgreement>(
			0);

	public Attachment() {
	}

	public Attachment(BigDecimal attachmentId) {
		this.attachmentId = attachmentId;
	}

	public Attachment(BigDecimal attachmentId, String name, String type,
			String route, Set<CommercialAgreement> commercialAgreements) {
		this.attachmentId = attachmentId;
		this.name = name;
		this.type = type;
		this.route = route;
		this.commercialAgreements = commercialAgreements;
	}

	@Id
	@Column(name = "ATTACHMENT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(BigDecimal attachmentId) {
		this.attachmentId = attachmentId;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TYPE", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "ROUTE", length = 500)
	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attachment")
	public Set<CommercialAgreement> getCommercialAgreements() {
		return this.commercialAgreements;
	}

	public void setCommercialAgreements(
			Set<CommercialAgreement> commercialAgreements) {
		this.commercialAgreements = commercialAgreements;
	}

}
