package com.beco.portalproveedores.bean;

// Generated 27/03/2014 04:21:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "CATEGORY")
public class Category implements java.io.Serializable {

	private BigDecimal categoryId;
	private String categoryName;

	public Category() {
	}

	public Category(BigDecimal categoryId) {
		this.categoryId = categoryId;
	}

	public Category(BigDecimal categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	@Id
	@Column(name = "CATEGORY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(BigDecimal categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "CATEGORY_NAME", length = 100)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

}
