package com.beco.portalproveedores.bean;

// Generated 14/02/2014 09:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommercialAgreement generated by hbm2java
 */
@Entity
@Table(name = "COMMERCIAL_AGREEMENT")
public class CommercialAgreement implements java.io.Serializable {

	private BigDecimal commercialAgreementId;
	private Attachment attachment;
	private Prospect prospect;
	private Double discGosPerc;
	private Double discGosAmou;
	private Double discOpeningPerc;
	private Double discOpeningAmou;
	private Double discAfterSalePerc;
	private Double discAfterSaleAmou;
	private Double discDeliCentralPerc;
	private Double discDeliCentralAmou;
	private Double discRecogMermaPerc;
	private Double discRecogMermaAmou;
	private Double discFixedVolumePerc;
	private Double discFixedVolumeAmou;
	private Double firstVarVolDiscFrom;
	private Double firstVarVolDiscTo;
	private Double firstVarVolDiscPerc;
	private Double secondVarVolDiscFrom;
	private Double secondVarVolDiscTo;
	private Double secondVarVolDiscPerc;
	private Double advertisingContrPerc;
	private String currency;
	private String status;

	public CommercialAgreement() {
	}

	public CommercialAgreement(BigDecimal commercialAgreementId) {
		this.commercialAgreementId = commercialAgreementId;
	}

	public CommercialAgreement(BigDecimal commercialAgreementId,
			Attachment attachment, Prospect prospect, Double discGosPerc,
			Double discGosAmou, Double discOpeningPerc, Double discOpeningAmou,
			Double discAfterSalePerc, Double discAfterSaleAmou,
			Double discDeliCentralPerc, Double discDeliCentralAmou,
			Double discRecogMermaPerc, Double discRecogMermaAmou,
			Double discFixedVolumePerc, Double discFixedVolumeAmou,
			Double firstVarVolDiscFrom, Double firstVarVolDiscTo,
			Double firstVarVolDiscPerc, Double secondVarVolDiscFrom,
			Double secondVarVolDiscTo, Double secondVarVolDiscPerc,
			Double advertisingContrPerc, String currency, String status) {
		this.commercialAgreementId = commercialAgreementId;
		this.attachment = attachment;
		this.prospect = prospect;
		this.discGosPerc = discGosPerc;
		this.discGosAmou = discGosAmou;
		this.discOpeningPerc = discOpeningPerc;
		this.discOpeningAmou = discOpeningAmou;
		this.discAfterSalePerc = discAfterSalePerc;
		this.discAfterSaleAmou = discAfterSaleAmou;
		this.discDeliCentralPerc = discDeliCentralPerc;
		this.discDeliCentralAmou = discDeliCentralAmou;
		this.discRecogMermaPerc = discRecogMermaPerc;
		this.discRecogMermaAmou = discRecogMermaAmou;
		this.discFixedVolumePerc = discFixedVolumePerc;
		this.discFixedVolumeAmou = discFixedVolumeAmou;
		this.firstVarVolDiscFrom = firstVarVolDiscFrom;
		this.firstVarVolDiscTo = firstVarVolDiscTo;
		this.firstVarVolDiscPerc = firstVarVolDiscPerc;
		this.secondVarVolDiscFrom = secondVarVolDiscFrom;
		this.secondVarVolDiscTo = secondVarVolDiscTo;
		this.secondVarVolDiscPerc = secondVarVolDiscPerc;
		this.advertisingContrPerc = advertisingContrPerc;
		this.currency = currency;
		this.status = status;
	}

	@Id
	@Column(name = "COMMERCIAL_AGREEMENT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCommercialAgreementId() {
		return this.commercialAgreementId;
	}

	public void setCommercialAgreementId(BigDecimal commercialAgreementId) {
		this.commercialAgreementId = commercialAgreementId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATTACHMENT_ID")
	public Attachment getAttachment() {
		return this.attachment;
	}

	public void setAttachment(Attachment attachment) {
		this.attachment = attachment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROSPECT_ID")
	public Prospect getProspect() {
		return this.prospect;
	}

	public void setProspect(Prospect prospect) {
		this.prospect = prospect;
	}

	@Column(name = "DISC_GOS_PERC", precision = 18, scale = 0)
	public Double getDiscGosPerc() {
		return this.discGosPerc;
	}

	public void setDiscGosPerc(Double discGosPerc) {
		this.discGosPerc = discGosPerc;
	}

	@Column(name = "DISC_GOS_AMOU", precision = 18, scale = 0)
	public Double getDiscGosAmou() {
		return this.discGosAmou;
	}

	public void setDiscGosAmou(Double discGosAmou) {
		this.discGosAmou = discGosAmou;
	}

	@Column(name = "DISC_OPENING_PERC", precision = 18, scale = 0)
	public Double getDiscOpeningPerc() {
		return this.discOpeningPerc;
	}

	public void setDiscOpeningPerc(Double discOpeningPerc) {
		this.discOpeningPerc = discOpeningPerc;
	}

	@Column(name = "DISC_OPENING_AMOU", precision = 18, scale = 0)
	public Double getDiscOpeningAmou() {
		return this.discOpeningAmou;
	}

	public void setDiscOpeningAmou(Double discOpeningAmou) {
		this.discOpeningAmou = discOpeningAmou;
	}

	@Column(name = "DISC_AFTER_SALE_PERC", precision = 18, scale = 0)
	public Double getDiscAfterSalePerc() {
		return this.discAfterSalePerc;
	}

	public void setDiscAfterSalePerc(Double discAfterSalePerc) {
		this.discAfterSalePerc = discAfterSalePerc;
	}

	@Column(name = "DISC_AFTER_SALE_AMOU", precision = 18, scale = 0)
	public Double getDiscAfterSaleAmou() {
		return this.discAfterSaleAmou;
	}

	public void setDiscAfterSaleAmou(Double discAfterSaleAmou) {
		this.discAfterSaleAmou = discAfterSaleAmou;
	}

	@Column(name = "DISC_DELI_CENTRAL_PERC", precision = 18, scale = 0)
	public Double getDiscDeliCentralPerc() {
		return this.discDeliCentralPerc;
	}

	public void setDiscDeliCentralPerc(Double discDeliCentralPerc) {
		this.discDeliCentralPerc = discDeliCentralPerc;
	}

	@Column(name = "DISC_DELI_CENTRAL_AMOU", precision = 18, scale = 0)
	public Double getDiscDeliCentralAmou() {
		return this.discDeliCentralAmou;
	}

	public void setDiscDeliCentralAmou(Double discDeliCentralAmou) {
		this.discDeliCentralAmou = discDeliCentralAmou;
	}

	@Column(name = "DISC_RECOG_MERMA_PERC", precision = 18, scale = 0)
	public Double getDiscRecogMermaPerc() {
		return this.discRecogMermaPerc;
	}

	public void setDiscRecogMermaPerc(Double discRecogMermaPerc) {
		this.discRecogMermaPerc = discRecogMermaPerc;
	}

	@Column(name = "DISC_RECOG_MERMA_AMOU", precision = 18, scale = 0)
	public Double getDiscRecogMermaAmou() {
		return this.discRecogMermaAmou;
	}

	public void setDiscRecogMermaAmou(Double discRecogMermaAmou) {
		this.discRecogMermaAmou = discRecogMermaAmou;
	}

	@Column(name = "DISC_FIXED_VOLUME_PERC", precision = 18, scale = 0)
	public Double getDiscFixedVolumePerc() {
		return this.discFixedVolumePerc;
	}

	public void setDiscFixedVolumePerc(Double discFixedVolumePerc) {
		this.discFixedVolumePerc = discFixedVolumePerc;
	}

	@Column(name = "DISC_FIXED_VOLUME_AMOU", precision = 18, scale = 0)
	public Double getDiscFixedVolumeAmou() {
		return this.discFixedVolumeAmou;
	}

	public void setDiscFixedVolumeAmou(Double discFixedVolumeAmou) {
		this.discFixedVolumeAmou = discFixedVolumeAmou;
	}

	@Column(name = "FIRST_VAR_VOL_DISC_FROM", precision = 18, scale = 0)
	public Double getFirstVarVolDiscFrom() {
		return this.firstVarVolDiscFrom;
	}

	public void setFirstVarVolDiscFrom(Double firstVarVolDiscFrom) {
		this.firstVarVolDiscFrom = firstVarVolDiscFrom;
	}

	@Column(name = "FIRST_VAR_VOL_DISC_TO", precision = 18, scale = 0)
	public Double getFirstVarVolDiscTo() {
		return this.firstVarVolDiscTo;
	}

	public void setFirstVarVolDiscTo(Double firstVarVolDiscTo) {
		this.firstVarVolDiscTo = firstVarVolDiscTo;
	}

	@Column(name = "FIRST_VAR_VOL_DISC_PERC", precision = 18, scale = 0)
	public Double getFirstVarVolDiscPerc() {
		return this.firstVarVolDiscPerc;
	}

	public void setFirstVarVolDiscPerc(Double firstVarVolDiscPerc) {
		this.firstVarVolDiscPerc = firstVarVolDiscPerc;
	}

	@Column(name = "SECOND_VAR_VOL_DISC_FROM", precision = 18, scale = 0)
	public Double getSecondVarVolDiscFrom() {
		return this.secondVarVolDiscFrom;
	}

	public void setSecondVarVolDiscFrom(Double secondVarVolDiscFrom) {
		this.secondVarVolDiscFrom = secondVarVolDiscFrom;
	}

	@Column(name = "SECOND_VAR_VOL_DISC_TO", precision = 18, scale = 0)
	public Double getSecondVarVolDiscTo() {
		return this.secondVarVolDiscTo;
	}

	public void setSecondVarVolDiscTo(Double secondVarVolDiscTo) {
		this.secondVarVolDiscTo = secondVarVolDiscTo;
	}

	@Column(name = "SECOND_VAR_VOL_DISC_PERC", precision = 18, scale = 0)
	public Double getSecondVarVolDiscPerc() {
		return this.secondVarVolDiscPerc;
	}

	public void setSecondVarVolDiscPerc(Double secondVarVolDiscPerc) {
		this.secondVarVolDiscPerc = secondVarVolDiscPerc;
	}

	@Column(name = "ADVERTISING_CONTR_PERC", precision = 18, scale = 0)
	public Double getAdvertisingContrPerc() {
		return this.advertisingContrPerc;
	}

	public void setAdvertisingContrPerc(Double advertisingContrPerc) {
		this.advertisingContrPerc = advertisingContrPerc;
	}

	@Column(name = "CURRENCY", length = 50)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
