package com.beco.portalproveedores.bean;

// Generated 27/03/2014 04:21:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "DEPARTMENT")
public class Department implements java.io.Serializable {

	private BigDecimal departmentId;
	private String departmentName;
	private String departmentCategory;

	public Department() {
	}

	public Department(BigDecimal departmentId) {
		this.departmentId = departmentId;
	}

	public Department(BigDecimal departmentId, String departmentName,
			String departmentCategory) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
		this.departmentCategory = departmentCategory;
	}

	@Id
	@Column(name = "DEPARTMENT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(BigDecimal departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "DEPARTMENT_NAME", length = 100)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "DEPARTMENT_CATEGORY", length = 100)
	public String getDepartmentCategory() {
		return this.departmentCategory;
	}

	public void setDepartmentCategory(String departmentCategory) {
		this.departmentCategory = departmentCategory;
	}

}
