package com.beco.portalproveedores.bean;

// Generated 14/03/2014 04:13:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Origin generated by hbm2java
 */
@Entity
@Table(name = "ORIGIN")
public class Origin implements java.io.Serializable {

	private BigDecimal originId;
	private String originName;

	public Origin() {
	}

	public Origin(BigDecimal originId) {
		this.originId = originId;
	}

	public Origin(BigDecimal originId, String originName) {
		this.originId = originId;
		this.originName = originName;
	}

	@Id
	@Column(name = "ORIGIN_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getOriginId() {
		return this.originId;
	}

	public void setOriginId(BigDecimal originId) {
		this.originId = originId;
	}

	@Column(name = "ORIGIN_NAME", length = 50)
	public String getOriginName() {
		return this.originName;
	}

	public void setOriginName(String originName) {
		this.originName = originName;
	}

}
