package com.beco.portalproveedores.bean;

// Generated 14/02/2014 09:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "PERMISSION")
public class Permission implements java.io.Serializable {

	private BigDecimal permissionId;
	private String name;
	private Set<RolePermission> rolePermissions = new HashSet<RolePermission>(0);

	public Permission() {
	}

	public Permission(BigDecimal permissionId) {
		this.permissionId = permissionId;
	}

	public Permission(BigDecimal permissionId, String name,
			Set<RolePermission> rolePermissions) {
		this.permissionId = permissionId;
		this.name = name;
		this.rolePermissions = rolePermissions;
	}

	@Id
	@Column(name = "PERMISSION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(BigDecimal permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permission")
	public Set<RolePermission> getRolePermissions() {
		return this.rolePermissions;
	}

	public void setRolePermissions(Set<RolePermission> rolePermissions) {
		this.rolePermissions = rolePermissions;
	}

}
