package com.beco.portalproveedores.bean;

// Generated 14/02/2014 09:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductProspect generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_PROSPECT")
public class ProductProspect implements java.io.Serializable {

	private BigDecimal productProspectId;
	private Product product;
	private Prospect prospect;

	public ProductProspect() {
	}

	public ProductProspect(BigDecimal productProspectId) {
		this.productProspectId = productProspectId;
	}

	public ProductProspect(BigDecimal productProspectId, Product product,
			Prospect prospect) {
		this.productProspectId = productProspectId;
		this.product = product;
		this.prospect = prospect;
	}

	@Id
	@Column(name = "PRODUCT_PROSPECT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProductProspectId() {
		return this.productProspectId;
	}

	public void setProductProspectId(BigDecimal productProspectId) {
		this.productProspectId = productProspectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROSPECT_ID")
	public Prospect getProspect() {
		return this.prospect;
	}

	public void setProspect(Prospect prospect) {
		this.prospect = prospect;
	}

}
