package com.beco.portalproveedores.bean;

// Generated 14/02/2014 09:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT")
public class Product implements java.io.Serializable {

	private BigDecimal productId;
	private String category;
	private String department;
	private String line;
	private String section;
	private Set<ProductProspect> productProspects = new HashSet<ProductProspect>(
			0);

	public Product() {
	}

	public Product(BigDecimal productId) {
		this.productId = productId;
	}

	public Product(BigDecimal productId, String category, String department,
			String line, String section, Set<ProductProspect> productProspects) {
		this.productId = productId;
		this.category = category;
		this.department = department;
		this.line = line;
		this.section = section;
		this.productProspects = productProspects;
	}

	@Id
	@Column(name = "PRODUCT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProductId() {
		return this.productId;
	}

	public void setProductId(BigDecimal productId) {
		this.productId = productId;
	}

	@Column(name = "CATEGORY", length = 50)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "DEPARTMENT", length = 50)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "LINE", length = 50)
	public String getLine() {
		return this.line;
	}

	public void setLine(String line) {
		this.line = line;
	}

	@Column(name = "SECTION", length = 50)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductProspect> getProductProspects() {
		return this.productProspects;
	}

	public void setProductProspects(Set<ProductProspect> productProspects) {
		this.productProspects = productProspects;
	}

}
