package com.beco.portalproveedores.bean;

// Generated 28/03/2014 02:09:19 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProspectCategory generated by hbm2java
 */
@Entity
@Table(name = "PROSPECT_CATEGORY")
public class ProspectCategory implements java.io.Serializable {

	private BigDecimal prospectCategoryId;
	private Prospect prospect;
	private Category category;

	public ProspectCategory() {
	}

	public ProspectCategory(BigDecimal prospectCategoryId) {
		this.prospectCategoryId = prospectCategoryId;
	}

	public ProspectCategory(BigDecimal prospectCategoryId, Prospect prospect,
			Category category) {
		this.prospectCategoryId = prospectCategoryId;
		this.prospect = prospect;
		this.category = category;
	}

	@Id
	@Column(name = "PROSPECT_CATEGORY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProspectCategoryId() {
		return this.prospectCategoryId;
	}

	public void setProspectCategoryId(BigDecimal prospectCategoryId) {
		this.prospectCategoryId = prospectCategoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROSPECT_ID")
	public Prospect getProspect() {
		return this.prospect;
	}

	public void setProspect(Prospect prospect) {
		this.prospect = prospect;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATEGORY_ID")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

}
