package com.beco.portalproveedores.bean;

// Generated 28/03/2014 02:09:19 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProspectLine generated by hbm2java
 */
@Entity
@Table(name = "PROSPECT_LINE")
public class ProspectLine implements java.io.Serializable {

	private BigDecimal prospectLineId;
	private Line line;
	private Prospect prospect;

	public ProspectLine() {
	}

	public ProspectLine(BigDecimal prospectLineId) {
		this.prospectLineId = prospectLineId;
	}

	public ProspectLine(BigDecimal prospectLineId, Line line, Prospect prospect) {
		this.prospectLineId = prospectLineId;
		this.line = line;
		this.prospect = prospect;
	}

	@Id
	@Column(name = "PROSPECT_LINE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProspectLineId() {
		return this.prospectLineId;
	}

	public void setProspectLineId(BigDecimal prospectLineId) {
		this.prospectLineId = prospectLineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LINE_ID")
	public Line getLine() {
		return this.line;
	}

	public void setLine(Line line) {
		this.line = line;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROSPECT_ID")
	public Prospect getProspect() {
		return this.prospect;
	}

	public void setProspect(Prospect prospect) {
		this.prospect = prospect;
	}

}
