package com.beco.portalproveedores.bean;

// Generated 14/02/2014 09:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prospect generated by hbm2java
 */
@Entity
@Table(name = "PROSPECT")
public class Prospect implements java.io.Serializable {

	private BigDecimal prospectId;
	private String commercialName;
	private String rifCi;
	private String phone;
	private String phone2;
	private String email;
	private String website;
	private String status;
	private Date statusUpdateDate;
	private String statusUpdateBy;
	private String statusDetails;
	private String country;
	private String contactPerson;
	private String origin;
	private String originDetails;
	private String observation;
	private String assets;
	private String products;
	private String services;
	private String approvedFinance;
	private String approvedBoss;
	private String address;
	private String fax;
	private String personType;
	private Date recordDate;
	private String economicActivity;
	private String paymentCondition;
	private String methodPayment;
	private String bank;
	private String accountNumber;
	private String fiscalName;
	private String legalContact;
	private String legalContactPhone;
	private String legalContactEmail;
	private String salesContact;
	private String salesContactPhone;
	private String salesContactEmail;
	private String adminContact;
	private String adminContactPhone;
	private String adminContactEmail;	
	private String expirationDateRif;
	private Set<CommercialAgreement> commercialAgreements = new HashSet<CommercialAgreement>(
			0);
	private Set<ProductProspect> productProspects = new HashSet<ProductProspect>(
			0);

	public Prospect() {
	}

	public Prospect(BigDecimal prospectId, String commercialName) {
		this.prospectId = prospectId;
		this.commercialName = commercialName;
	}

	public Prospect(BigDecimal prospectId, String commercialName, String rifCi,
			String phone, String phone2, String email, String website,
			String status, Date statusUpdateDate, String statusUpdateBy,
			String statusDetails, String country, String contactPerson,
			String origin, String originDetails, String observation,
			String assets, String products, String services,
			String approvedFinance, String approvedBoss, String address,
			String fax, String personType, Date recordDate,
			String economicActivity, String paymentCondition,
			String methodPayment, String bank, String accountNumber,
			String fiscalName, String legalContact, String legalContactPhone,
			String legalContactEmail, String salesContact,
			String salesContactPhone, String salesContactEmail,
			String adminContact, String adminContactPhone,
			String adminContactEmail, String expirationDateRif, 
			Set<CommercialAgreement> commercialAgreements,
			Set<ProductProspect> productProspects) {
		this.prospectId = prospectId;
		this.commercialName = commercialName;
		this.rifCi = rifCi;
		this.phone = phone;
		this.phone2 = phone2;
		this.email = email;
		this.website = website;
		this.status = status;
		this.statusUpdateDate = statusUpdateDate;
		this.statusUpdateBy = statusUpdateBy;
		this.statusDetails = statusDetails;
		this.country = country;
		this.contactPerson = contactPerson;
		this.origin = origin;
		this.originDetails = originDetails;
		this.observation = observation;
		this.assets = assets;
		this.products = products;
		this.services = services;
		this.approvedFinance = approvedFinance;
		this.approvedBoss = approvedBoss;
		this.address = address;
		this.fax = fax;
		this.personType = personType;
		this.recordDate = recordDate;
		this.economicActivity = economicActivity;
		this.paymentCondition = paymentCondition;
		this.methodPayment = methodPayment;
		this.bank = bank;
		this.accountNumber = accountNumber;
		this.fiscalName = fiscalName;
		this.legalContact = legalContact;
		this.legalContactPhone = legalContactPhone;
		this.legalContactEmail = legalContactEmail;
		this.salesContact = salesContact;
		this.salesContactPhone = salesContactPhone;
		this.salesContactEmail = salesContactEmail;
		this.adminContact = adminContact;
		this.adminContactPhone = adminContactPhone;
		this.adminContactEmail = adminContactEmail;
		this.commercialAgreements = commercialAgreements;
		this.productProspects = productProspects;
		this.expirationDateRif = expirationDateRif;
		
	}

	@Id
	@Column(name = "PROSPECT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProspectId() {
		return this.prospectId;
	}

	public void setProspectId(BigDecimal prospectId) {
		this.prospectId = prospectId;
	}

	@Column(name = "COMMERCIAL_NAME", nullable = false, length = 100)
	public String getCommercialName() {
		return this.commercialName;
	}

	public void setCommercialName(String commercialName) {
		this.commercialName = commercialName;
	}

	@Column(name = "RIF_CI", length = 20)
	public String getRifCi() {
		return this.rifCi;
	}

	public void setRifCi(String rifCi) {
		this.rifCi = rifCi;
	}

	@Column(name = "PHONE", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "PHONE_2", length = 20)
	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "WEBSITE", length = 50)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STATUS_UPDATE_DATE", length = 7)
	public Date getStatusUpdateDate() {
		return this.statusUpdateDate;
	}

	public void setStatusUpdateDate(Date statusUpdateDate) {
		this.statusUpdateDate = statusUpdateDate;
	}

	@Column(name = "STATUS_UPDATE_BY", length = 20)
	public String getStatusUpdateBy() {
		return this.statusUpdateBy;
	}

	public void setStatusUpdateBy(String statusUpdateBy) {
		this.statusUpdateBy = statusUpdateBy;
	}

	@Column(name = "STATUS_DETAILS", length = 50)
	public String getStatusDetails() {
		return this.statusDetails;
	}

	public void setStatusDetails(String statusDetails) {
		this.statusDetails = statusDetails;
	}

	@Column(name = "COUNTRY", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "CONTACT_PERSON", length = 50)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "ORIGIN", length = 50)
	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	@Column(name = "ORIGIN_DETAILS", length = 100)
	public String getOriginDetails() {
		return this.originDetails;
	}

	public void setOriginDetails(String originDetails) {
		this.originDetails = originDetails;
	}

	@Column(name = "OBSERVATION", length = 500)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "ASSETS", length = 5)
	public String getAssets() {
		return this.assets;
	}

	public void setAssets(String assets) {
		this.assets = assets;
	}

	@Column(name = "PRODUCTS", length = 5)
	public String getProducts() {
		return this.products;
	}

	public void setProducts(String products) {
		this.products = products;
	}

	@Column(name = "SERVICES", length = 5)
	public String getServices() {
		return this.services;
	}

	public void setServices(String services) {
		this.services = services;
	}

	@Column(name = "APPROVED_FINANCE", length = 5)
	public String getApprovedFinance() {
		return this.approvedFinance;
	}

	public void setApprovedFinance(String approvedFinance) {
		this.approvedFinance = approvedFinance;
	}

	@Column(name = "APPROVED_BOSS", length = 5)
	public String getApprovedBoss() {
		return this.approvedBoss;
	}

	public void setApprovedBoss(String approvedBoss) {
		this.approvedBoss = approvedBoss;
	}

	@Column(name = "ADDRESS", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "PERSON_TYPE", length = 50)
	public String getPersonType() {
		return this.personType;
	}

	public void setPersonType(String personType) {
		this.personType = personType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RECORD_DATE", length = 7)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@Column(name = "ECONOMIC_ACTIVITY", length = 50)
	public String getEconomicActivity() {
		return this.economicActivity;
	}

	public void setEconomicActivity(String economicActivity) {
		this.economicActivity = economicActivity;
	}

	@Column(name = "PAYMENT_CONDITION", length = 50)
	public String getPaymentCondition() {
		return this.paymentCondition;
	}

	public void setPaymentCondition(String paymentCondition) {
		this.paymentCondition = paymentCondition;
	}

	@Column(name = "METHOD_PAYMENT", length = 50)
	public String getMethodPayment() {
		return this.methodPayment;
	}

	public void setMethodPayment(String methodPayment) {
		this.methodPayment = methodPayment;
	}

	@Column(name = "BANK", length = 100)
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	@Column(name = "ACCOUNT_NUMBER", length = 50)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "FISCAL_NAME", length = 200)
	public String getFiscalName() {
		return this.fiscalName;
	}

	public void setFiscalName(String fiscalName) {
		this.fiscalName = fiscalName;
	}

	@Column(name = "LEGAL_CONTACT", length = 50)
	public String getLegalContact() {
		return this.legalContact;
	}

	public void setLegalContact(String legalContact) {
		this.legalContact = legalContact;
	}

	@Column(name = "LEGAL_CONTACT_PHONE", length = 50)
	public String getLegalContactPhone() {
		return this.legalContactPhone;
	}

	public void setLegalContactPhone(String legalContactPhone) {
		this.legalContactPhone = legalContactPhone;
	}

	@Column(name = "LEGAL_CONTACT_EMAIL", length = 50)
	public String getLegalContactEmail() {
		return this.legalContactEmail;
	}

	public void setLegalContactEmail(String legalContactEmail) {
		this.legalContactEmail = legalContactEmail;
	}

	@Column(name = "SALES_CONTACT", length = 50)
	public String getSalesContact() {
		return this.salesContact;
	}

	public void setSalesContact(String salesContact) {
		this.salesContact = salesContact;
	}

	@Column(name = "SALES_CONTACT_PHONE", length = 50)
	public String getSalesContactPhone() {
		return this.salesContactPhone;
	}

	public void setSalesContactPhone(String salesContactPhone) {
		this.salesContactPhone = salesContactPhone;
	}

	@Column(name = "SALES_CONTACT_EMAIL", length = 50)
	public String getSalesContactEmail() {
		return this.salesContactEmail;
	}

	public void setSalesContactEmail(String salesContactEmail) {
		this.salesContactEmail = salesContactEmail;
	}

	@Column(name = "ADMIN_CONTACT", length = 50)
	public String getAdminContact() {
		return this.adminContact;
	}

	public void setAdminContact(String adminContact) {
		this.adminContact = adminContact;
	}

	@Column(name = "ADMIN_CONTACT_PHONE", length = 50)
	public String getAdminContactPhone() {
		return this.adminContactPhone;
	}

	public void setAdminContactPhone(String adminContactPhone) {
		this.adminContactPhone = adminContactPhone;
	}

	@Column(name = "ADMIN_CONTACT_EMAIL", length = 50)
	public String getAdminContactEmail() {
		return this.adminContactEmail;
	}

	public void setAdminContactEmail(String adminContactEmail) {
		this.adminContactEmail = adminContactEmail;
	}
	
	@Column(name = "EXPIRATION_DATE_RIF", length = 50)
	public String getExpirationDateRif() {
		return this.expirationDateRif;
	}

	public void setExpirationDateRif(String expirationDateRif) {
		this.expirationDateRif = expirationDateRif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prospect")
	public Set<CommercialAgreement> getCommercialAgreements() {
		return this.commercialAgreements;
	}

	public void setCommercialAgreements(
			Set<CommercialAgreement> commercialAgreements) {
		this.commercialAgreements = commercialAgreements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prospect")
	public Set<ProductProspect> getProductProspects() {
		return this.productProspects;
	}

	public void setProductProspects(Set<ProductProspect> productProspects) {
		this.productProspects = productProspects;
	}

}
