package com.beco.portalproveedores.bean;

// Generated 28/03/2014 02:09:19 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProspectSection generated by hbm2java
 */
@Entity
@Table(name = "PROSPECT_SECTION")
public class ProspectSection implements java.io.Serializable {

	private BigDecimal prospectSectionId;
	private Prospect prospect;
	private Section section;

	public ProspectSection() {
	}

	public ProspectSection(BigDecimal prospectSectionId) {
		this.prospectSectionId = prospectSectionId;
	}

	public ProspectSection(BigDecimal prospectSectionId, Prospect prospect,
			Section section) {
		this.prospectSectionId = prospectSectionId;
		this.prospect = prospect;
		this.section = section;
	}

	@Id
	@Column(name = "PROSPECT_SECTION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProspectSectionId() {
		return this.prospectSectionId;
	}

	public void setProspectSectionId(BigDecimal prospectSectionId) {
		this.prospectSectionId = prospectSectionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROSPECT_ID")
	public Prospect getProspect() {
		return this.prospect;
	}

	public void setProspect(Prospect prospect) {
		this.prospect = prospect;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECTION_ID")
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

}
