package com.beco.portalproveedores.bean;

// Generated 28/03/2014 02:09:19 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProspectDepartment generated by hbm2java
 */
@Entity
@Table(name = "PROSPECT_DEPARTMENT")
public class ProspectDepartment implements java.io.Serializable {

	private BigDecimal prospectDepartmentId;
	private Prospect prospect;
	private Department department;

	public ProspectDepartment() {
	}

	public ProspectDepartment(BigDecimal prospectDepartmentId) {
		this.prospectDepartmentId = prospectDepartmentId;
	}

	public ProspectDepartment(BigDecimal prospectDepartmentId,
			Prospect prospect, Department department) {
		this.prospectDepartmentId = prospectDepartmentId;
		this.prospect = prospect;
		this.department = department;
	}

	@Id
	@Column(name = "PROSPECT_DEPARTMENT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProspectDepartmentId() {
		return this.prospectDepartmentId;
	}

	public void setProspectDepartmentId(BigDecimal prospectDepartmentId) {
		this.prospectDepartmentId = prospectDepartmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROSPECT_ID")
	public Prospect getProspect() {
		return this.prospect;
	}

	public void setProspect(Prospect prospect) {
		this.prospect = prospect;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPARTMENT_ID")
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

}
