package com.beco.portalproveedores.bean;

// Generated 14/02/2014 09:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolePermission generated by hbm2java
 */
@Entity
@Table(name = "ROLE_PERMISSION")
public class RolePermission implements java.io.Serializable {

	private BigDecimal rolePermissionId;
	private Role role;
	private Permission permission;

	public RolePermission() {
	}

	public RolePermission(BigDecimal rolePermissionId) {
		this.rolePermissionId = rolePermissionId;
	}

	public RolePermission(BigDecimal rolePermissionId, Role role,
			Permission permission) {
		this.rolePermissionId = rolePermissionId;
		this.role = role;
		this.permission = permission;
	}

	@Id
	@Column(name = "ROLE_PERMISSION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRolePermissionId() {
		return this.rolePermissionId;
	}

	public void setRolePermissionId(BigDecimal rolePermissionId) {
		this.rolePermissionId = rolePermissionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMISSION_ID")
	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

}
