package com.beco.portalproveedores.bean;

// Generated 14/02/2014 09:52:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RoleUserPortal generated by hbm2java
 */
@Entity
@Table(name = "ROLE_USER_PORTAL")
public class RoleUserPortal implements java.io.Serializable {

	private BigDecimal roleUserPortalId;
	private BigDecimal rolePortal;
	private BigDecimal userPortal;

	public RoleUserPortal() {
	}

	public RoleUserPortal(BigDecimal roleUserPortalId) {
		this.roleUserPortalId = roleUserPortalId;
	}

	public RoleUserPortal(BigDecimal roleUserPortalId, BigDecimal rolePortal,
			BigDecimal userPortal) {
		this.roleUserPortalId = roleUserPortalId;
		this.rolePortal = rolePortal;
		this.userPortal = userPortal;
	}

	@Id
	@Column(name = "ROLE_USER_PORTAL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRoleUserPortalId() {
		return this.roleUserPortalId;
	}

	public void setRoleUserPortalId(BigDecimal roleUserPortalId) {
		this.roleUserPortalId = roleUserPortalId;
	}

	@Column(name = "ROLE_PORTAL", precision = 22, scale = 0)
	public BigDecimal getRolePortal() {
		return this.rolePortal;
	}

	public void setRolePortal(BigDecimal rolePortal) {
		this.rolePortal = rolePortal;
	}

	@Column(name = "USER_PORTAL", precision = 22, scale = 0)
	public BigDecimal getUserPortal() {
		return this.userPortal;
	}

	public void setUserPortal(BigDecimal userPortal) {
		this.userPortal = userPortal;
	}

}
