package com.beco.portalproveedores.bean;

// Generated 14/03/2014 04:13:57 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "STATUS")
public class Status implements java.io.Serializable {

	private BigDecimal statusId;
	private String statusName;

	public Status() {
	}

	public Status(BigDecimal statusId) {
		this.statusId = statusId;
	}

	public Status(BigDecimal statusId, String statusName) {
		this.statusId = statusId;
		this.statusName = statusName;
	}

	@Id
	@Column(name = "STATUS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getStatusId() {
		return this.statusId;
	}

	public void setStatusId(BigDecimal statusId) {
		this.statusId = statusId;
	}

	@Column(name = "STATUS_NAME", length = 50)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

}
